eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 11010
spring:
  application:
    name: eurekaclient
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
